In [1]:
import numpy as np

A = np.array([[3, 4], [6, 8]])

B = np.array([[1, 7],[9, 7]])

result = A + B

print("Array A:")
print(A)

print("\nArray B:")
print(B)

print("\nAddition of A and B:")
print(result)


Array A:
[[3 4]
 [6 8]]

Array B:
[[1 7]
 [9 7]]

Addition of A and B:
[[ 4 11]
 [15 15]]
